[build-system]
requires = [
    "setuptools>=54.0",
    "setuptools_scm[toml]>=5.0",
    "wheel>=0.36.2",
    "Cython>=3.0.10",
    "tomli",
    ]

[tool.setuptools_scm]
write_to = "src/pymssql/version.h"
write_to_template = 'const char* PYMSSQL_VERSION = "{version}";'
local_scheme = "no-local-version"

[tool.freetds]
version_for_pypi_wheels = "1.4.22"
