name: Build Wheels

on:
  push:
    branches:
        - '**'
    paths-ignore:
        - docs/**
        - ChangeLog*
    tags:
        - 'v[0-9]+.[0-9]+.[0-9]+'
        - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
  pull_request:
    branches:
        - '**'
    paths-ignore:
        - docs/**
        - ChangeLog*

  workflow_dispatch:

jobs:

  build_wheels:

    name: Build wheels on ${{ matrix.os }} on Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        #os: [macos-latest, ubuntu-20.04]
        #os: [ubuntu-20.04, ubuntu-24.04-arm, windows-latest]
        #os: [windows-latest]
        include:
        - os: ubuntu-latest
          arch: x86_64
          id: cp3*-manylinux_x86_64
        - os: ubuntu-24.04-arm
          arch: aarch64
          id: cp3*-manylinux_aarch64
        - os: macos-13
          arch: x86_64
          id: cp3*-macos_x86_64
        - os: macos-15
          arch: arm64
          id: cp3*-macos_arm64
        - os: windows-latest
          arch: amd64
          id: cp3*-win_amd64

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: aarch64

      - name: Build wheels
        env:
            CIBW_ARCHS: ${{ matrix.arch }}
            CIBW_ARCHS_MACOS: ${{ matrix.arch }}
            CIBW_BUILD: ${{ matrix.id }}

        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse

  upload-wheels:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: wheels
          #path: wheelhouse
          pattern: wheels-*
          separate-directories: false
          delete-merged: false
